# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake

# The command to remove a file.
RM = /home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wuwj/workdir/G410code/geant4/simjuno

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wuwj/workdir/G410code/geant4/simjuno

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/juno/soft/cmake/cmake-3.9.2-install/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wuwj/workdir/G410code/geant4/simjuno/CMakeFiles /home/wuwj/workdir/G410code/geant4/simjuno/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wuwj/workdir/G410code/geant4/simjuno/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named simjuno

# Build rule for target.
simjuno: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simjuno
.PHONY : simjuno

# fast build rule for target.
simjuno/fast:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/build
.PHONY : simjuno/fast

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/main.cc.s
.PHONY : main.cc.s

src/ActionInitialization.o: src/ActionInitialization.cc.o

.PHONY : src/ActionInitialization.o

# target to build an object file
src/ActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/ActionInitialization.cc.o
.PHONY : src/ActionInitialization.cc.o

src/ActionInitialization.i: src/ActionInitialization.cc.i

.PHONY : src/ActionInitialization.i

# target to preprocess a source file
src/ActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/ActionInitialization.cc.i
.PHONY : src/ActionInitialization.cc.i

src/ActionInitialization.s: src/ActionInitialization.cc.s

.PHONY : src/ActionInitialization.s

# target to generate assembly for a file
src/ActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/ActionInitialization.cc.s
.PHONY : src/ActionInitialization.cc.s

src/AnalysisManager.o: src/AnalysisManager.cc.o

.PHONY : src/AnalysisManager.o

# target to build an object file
src/AnalysisManager.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/AnalysisManager.cc.o
.PHONY : src/AnalysisManager.cc.o

src/AnalysisManager.i: src/AnalysisManager.cc.i

.PHONY : src/AnalysisManager.i

# target to preprocess a source file
src/AnalysisManager.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/AnalysisManager.cc.i
.PHONY : src/AnalysisManager.cc.i

src/AnalysisManager.s: src/AnalysisManager.cc.s

.PHONY : src/AnalysisManager.s

# target to generate assembly for a file
src/AnalysisManager.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/AnalysisManager.cc.s
.PHONY : src/AnalysisManager.cc.s

src/AnalysisManagerMessenger.o: src/AnalysisManagerMessenger.cc.o

.PHONY : src/AnalysisManagerMessenger.o

# target to build an object file
src/AnalysisManagerMessenger.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/AnalysisManagerMessenger.cc.o
.PHONY : src/AnalysisManagerMessenger.cc.o

src/AnalysisManagerMessenger.i: src/AnalysisManagerMessenger.cc.i

.PHONY : src/AnalysisManagerMessenger.i

# target to preprocess a source file
src/AnalysisManagerMessenger.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/AnalysisManagerMessenger.cc.i
.PHONY : src/AnalysisManagerMessenger.cc.i

src/AnalysisManagerMessenger.s: src/AnalysisManagerMessenger.cc.s

.PHONY : src/AnalysisManagerMessenger.s

# target to generate assembly for a file
src/AnalysisManagerMessenger.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/AnalysisManagerMessenger.cc.s
.PHONY : src/AnalysisManagerMessenger.cc.s

src/DetectorConstruction.o: src/DetectorConstruction.cc.o

.PHONY : src/DetectorConstruction.o

# target to build an object file
src/DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DetectorConstruction.cc.o
.PHONY : src/DetectorConstruction.cc.o

src/DetectorConstruction.i: src/DetectorConstruction.cc.i

.PHONY : src/DetectorConstruction.i

# target to preprocess a source file
src/DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DetectorConstruction.cc.i
.PHONY : src/DetectorConstruction.cc.i

src/DetectorConstruction.s: src/DetectorConstruction.cc.s

.PHONY : src/DetectorConstruction.s

# target to generate assembly for a file
src/DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DetectorConstruction.cc.s
.PHONY : src/DetectorConstruction.cc.s

src/DsG4OpAbsReemit.o: src/DsG4OpAbsReemit.cc.o

.PHONY : src/DsG4OpAbsReemit.o

# target to build an object file
src/DsG4OpAbsReemit.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4OpAbsReemit.cc.o
.PHONY : src/DsG4OpAbsReemit.cc.o

src/DsG4OpAbsReemit.i: src/DsG4OpAbsReemit.cc.i

.PHONY : src/DsG4OpAbsReemit.i

# target to preprocess a source file
src/DsG4OpAbsReemit.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4OpAbsReemit.cc.i
.PHONY : src/DsG4OpAbsReemit.cc.i

src/DsG4OpAbsReemit.s: src/DsG4OpAbsReemit.cc.s

.PHONY : src/DsG4OpAbsReemit.s

# target to generate assembly for a file
src/DsG4OpAbsReemit.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4OpAbsReemit.cc.s
.PHONY : src/DsG4OpAbsReemit.cc.s

src/DsG4ScintSimple.o: src/DsG4ScintSimple.cc.o

.PHONY : src/DsG4ScintSimple.o

# target to build an object file
src/DsG4ScintSimple.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4ScintSimple.cc.o
.PHONY : src/DsG4ScintSimple.cc.o

src/DsG4ScintSimple.i: src/DsG4ScintSimple.cc.i

.PHONY : src/DsG4ScintSimple.i

# target to preprocess a source file
src/DsG4ScintSimple.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4ScintSimple.cc.i
.PHONY : src/DsG4ScintSimple.cc.i

src/DsG4ScintSimple.s: src/DsG4ScintSimple.cc.s

.PHONY : src/DsG4ScintSimple.s

# target to generate assembly for a file
src/DsG4ScintSimple.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4ScintSimple.cc.s
.PHONY : src/DsG4ScintSimple.cc.s

src/DsG4Scintillation.o: src/DsG4Scintillation.cc.o

.PHONY : src/DsG4Scintillation.o

# target to build an object file
src/DsG4Scintillation.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4Scintillation.cc.o
.PHONY : src/DsG4Scintillation.cc.o

src/DsG4Scintillation.i: src/DsG4Scintillation.cc.i

.PHONY : src/DsG4Scintillation.i

# target to preprocess a source file
src/DsG4Scintillation.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4Scintillation.cc.i
.PHONY : src/DsG4Scintillation.cc.i

src/DsG4Scintillation.s: src/DsG4Scintillation.cc.s

.PHONY : src/DsG4Scintillation.s

# target to generate assembly for a file
src/DsG4Scintillation.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsG4Scintillation.cc.s
.PHONY : src/DsG4Scintillation.cc.s

src/DsPhysConsOptical.o: src/DsPhysConsOptical.cc.o

.PHONY : src/DsPhysConsOptical.o

# target to build an object file
src/DsPhysConsOptical.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsPhysConsOptical.cc.o
.PHONY : src/DsPhysConsOptical.cc.o

src/DsPhysConsOptical.i: src/DsPhysConsOptical.cc.i

.PHONY : src/DsPhysConsOptical.i

# target to preprocess a source file
src/DsPhysConsOptical.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsPhysConsOptical.cc.i
.PHONY : src/DsPhysConsOptical.cc.i

src/DsPhysConsOptical.s: src/DsPhysConsOptical.cc.s

.PHONY : src/DsPhysConsOptical.s

# target to generate assembly for a file
src/DsPhysConsOptical.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/DsPhysConsOptical.cc.s
.PHONY : src/DsPhysConsOptical.cc.s

src/EnergyTimeHit.o: src/EnergyTimeHit.cc.o

.PHONY : src/EnergyTimeHit.o

# target to build an object file
src/EnergyTimeHit.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EnergyTimeHit.cc.o
.PHONY : src/EnergyTimeHit.cc.o

src/EnergyTimeHit.i: src/EnergyTimeHit.cc.i

.PHONY : src/EnergyTimeHit.i

# target to preprocess a source file
src/EnergyTimeHit.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EnergyTimeHit.cc.i
.PHONY : src/EnergyTimeHit.cc.i

src/EnergyTimeHit.s: src/EnergyTimeHit.cc.s

.PHONY : src/EnergyTimeHit.s

# target to generate assembly for a file
src/EnergyTimeHit.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EnergyTimeHit.cc.s
.PHONY : src/EnergyTimeHit.cc.s

src/EnergyTimeSD.o: src/EnergyTimeSD.cc.o

.PHONY : src/EnergyTimeSD.o

# target to build an object file
src/EnergyTimeSD.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EnergyTimeSD.cc.o
.PHONY : src/EnergyTimeSD.cc.o

src/EnergyTimeSD.i: src/EnergyTimeSD.cc.i

.PHONY : src/EnergyTimeSD.i

# target to preprocess a source file
src/EnergyTimeSD.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EnergyTimeSD.cc.i
.PHONY : src/EnergyTimeSD.cc.i

src/EnergyTimeSD.s: src/EnergyTimeSD.cc.s

.PHONY : src/EnergyTimeSD.s

# target to generate assembly for a file
src/EnergyTimeSD.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EnergyTimeSD.cc.s
.PHONY : src/EnergyTimeSD.cc.s

src/EventAction.o: src/EventAction.cc.o

.PHONY : src/EventAction.o

# target to build an object file
src/EventAction.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EventAction.cc.o
.PHONY : src/EventAction.cc.o

src/EventAction.i: src/EventAction.cc.i

.PHONY : src/EventAction.i

# target to preprocess a source file
src/EventAction.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EventAction.cc.i
.PHONY : src/EventAction.cc.i

src/EventAction.s: src/EventAction.cc.s

.PHONY : src/EventAction.s

# target to generate assembly for a file
src/EventAction.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/EventAction.cc.s
.PHONY : src/EventAction.cc.s

src/LSExpDetectorConstructionMaterial.o: src/LSExpDetectorConstructionMaterial.cc.o

.PHONY : src/LSExpDetectorConstructionMaterial.o

# target to build an object file
src/LSExpDetectorConstructionMaterial.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/LSExpDetectorConstructionMaterial.cc.o
.PHONY : src/LSExpDetectorConstructionMaterial.cc.o

src/LSExpDetectorConstructionMaterial.i: src/LSExpDetectorConstructionMaterial.cc.i

.PHONY : src/LSExpDetectorConstructionMaterial.i

# target to preprocess a source file
src/LSExpDetectorConstructionMaterial.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/LSExpDetectorConstructionMaterial.cc.i
.PHONY : src/LSExpDetectorConstructionMaterial.cc.i

src/LSExpDetectorConstructionMaterial.s: src/LSExpDetectorConstructionMaterial.cc.s

.PHONY : src/LSExpDetectorConstructionMaterial.s

# target to generate assembly for a file
src/LSExpDetectorConstructionMaterial.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/LSExpDetectorConstructionMaterial.cc.s
.PHONY : src/LSExpDetectorConstructionMaterial.cc.s

src/LSExpPhysicsList.o: src/LSExpPhysicsList.cc.o

.PHONY : src/LSExpPhysicsList.o

# target to build an object file
src/LSExpPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/LSExpPhysicsList.cc.o
.PHONY : src/LSExpPhysicsList.cc.o

src/LSExpPhysicsList.i: src/LSExpPhysicsList.cc.i

.PHONY : src/LSExpPhysicsList.i

# target to preprocess a source file
src/LSExpPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/LSExpPhysicsList.cc.i
.PHONY : src/LSExpPhysicsList.cc.i

src/LSExpPhysicsList.s: src/LSExpPhysicsList.cc.s

.PHONY : src/LSExpPhysicsList.s

# target to generate assembly for a file
src/LSExpPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/LSExpPhysicsList.cc.s
.PHONY : src/LSExpPhysicsList.cc.s

src/PrimaryGeneratorAction.o: src/PrimaryGeneratorAction.cc.o

.PHONY : src/PrimaryGeneratorAction.o

# target to build an object file
src/PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/PrimaryGeneratorAction.cc.o
.PHONY : src/PrimaryGeneratorAction.cc.o

src/PrimaryGeneratorAction.i: src/PrimaryGeneratorAction.cc.i

.PHONY : src/PrimaryGeneratorAction.i

# target to preprocess a source file
src/PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/PrimaryGeneratorAction.cc.i
.PHONY : src/PrimaryGeneratorAction.cc.i

src/PrimaryGeneratorAction.s: src/PrimaryGeneratorAction.cc.s

.PHONY : src/PrimaryGeneratorAction.s

# target to generate assembly for a file
src/PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/PrimaryGeneratorAction.cc.s
.PHONY : src/PrimaryGeneratorAction.cc.s

src/RunAction.o: src/RunAction.cc.o

.PHONY : src/RunAction.o

# target to build an object file
src/RunAction.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/RunAction.cc.o
.PHONY : src/RunAction.cc.o

src/RunAction.i: src/RunAction.cc.i

.PHONY : src/RunAction.i

# target to preprocess a source file
src/RunAction.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/RunAction.cc.i
.PHONY : src/RunAction.cc.i

src/RunAction.s: src/RunAction.cc.s

.PHONY : src/RunAction.s

# target to generate assembly for a file
src/RunAction.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/RunAction.cc.s
.PHONY : src/RunAction.cc.s

src/StackingAction.o: src/StackingAction.cc.o

.PHONY : src/StackingAction.o

# target to build an object file
src/StackingAction.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/StackingAction.cc.o
.PHONY : src/StackingAction.cc.o

src/StackingAction.i: src/StackingAction.cc.i

.PHONY : src/StackingAction.i

# target to preprocess a source file
src/StackingAction.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/StackingAction.cc.i
.PHONY : src/StackingAction.cc.i

src/StackingAction.s: src/StackingAction.cc.s

.PHONY : src/StackingAction.s

# target to generate assembly for a file
src/StackingAction.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/StackingAction.cc.s
.PHONY : src/StackingAction.cc.s

src/SteppingAction.o: src/SteppingAction.cc.o

.PHONY : src/SteppingAction.o

# target to build an object file
src/SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/SteppingAction.cc.o
.PHONY : src/SteppingAction.cc.o

src/SteppingAction.i: src/SteppingAction.cc.i

.PHONY : src/SteppingAction.i

# target to preprocess a source file
src/SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/SteppingAction.cc.i
.PHONY : src/SteppingAction.cc.i

src/SteppingAction.s: src/SteppingAction.cc.s

.PHONY : src/SteppingAction.s

# target to generate assembly for a file
src/SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/simjuno.dir/build.make CMakeFiles/simjuno.dir/src/SteppingAction.cc.s
.PHONY : src/SteppingAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... simjuno"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ActionInitialization.o"
	@echo "... src/ActionInitialization.i"
	@echo "... src/ActionInitialization.s"
	@echo "... src/AnalysisManager.o"
	@echo "... src/AnalysisManager.i"
	@echo "... src/AnalysisManager.s"
	@echo "... src/AnalysisManagerMessenger.o"
	@echo "... src/AnalysisManagerMessenger.i"
	@echo "... src/AnalysisManagerMessenger.s"
	@echo "... src/DetectorConstruction.o"
	@echo "... src/DetectorConstruction.i"
	@echo "... src/DetectorConstruction.s"
	@echo "... src/DsG4OpAbsReemit.o"
	@echo "... src/DsG4OpAbsReemit.i"
	@echo "... src/DsG4OpAbsReemit.s"
	@echo "... src/DsG4ScintSimple.o"
	@echo "... src/DsG4ScintSimple.i"
	@echo "... src/DsG4ScintSimple.s"
	@echo "... src/DsG4Scintillation.o"
	@echo "... src/DsG4Scintillation.i"
	@echo "... src/DsG4Scintillation.s"
	@echo "... src/DsPhysConsOptical.o"
	@echo "... src/DsPhysConsOptical.i"
	@echo "... src/DsPhysConsOptical.s"
	@echo "... src/EnergyTimeHit.o"
	@echo "... src/EnergyTimeHit.i"
	@echo "... src/EnergyTimeHit.s"
	@echo "... src/EnergyTimeSD.o"
	@echo "... src/EnergyTimeSD.i"
	@echo "... src/EnergyTimeSD.s"
	@echo "... src/EventAction.o"
	@echo "... src/EventAction.i"
	@echo "... src/EventAction.s"
	@echo "... src/LSExpDetectorConstructionMaterial.o"
	@echo "... src/LSExpDetectorConstructionMaterial.i"
	@echo "... src/LSExpDetectorConstructionMaterial.s"
	@echo "... src/LSExpPhysicsList.o"
	@echo "... src/LSExpPhysicsList.i"
	@echo "... src/LSExpPhysicsList.s"
	@echo "... src/PrimaryGeneratorAction.o"
	@echo "... src/PrimaryGeneratorAction.i"
	@echo "... src/PrimaryGeneratorAction.s"
	@echo "... src/RunAction.o"
	@echo "... src/RunAction.i"
	@echo "... src/RunAction.s"
	@echo "... src/StackingAction.o"
	@echo "... src/StackingAction.i"
	@echo "... src/StackingAction.s"
	@echo "... src/SteppingAction.o"
	@echo "... src/SteppingAction.i"
	@echo "... src/SteppingAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

