# This macro just runs one single particle
# to prove that the application works
#
# Run it using "./task macros/basic.mac"
/Optical/phys/verbose 0
/tracking/verbose 2
/histo/fileName toBeDelete.root
/Optical/phys/TruePhysics false
/run/initialize
/JUNO/primary/setRandom false
/random/setSeeds 0 1
/gun/particle opticalphoton
/gun/energy 3 eV
/gun/position 0 0 0 m
/gun/direction 0 0 1
/run/beamOn 100
